### ISSUE TITLE
Change Batch-size per GPU

### ISSUE THREAD

**Issue by th0214** [hanoonaR/object-centric-ovd#11]
Thanks for your great work.
It says DATASET_BS: [2, 8] based on 8 gpu, but if you use 2 gpu, can you explain how to fix DATASET_BS?
Can you also tell me what 2 and 8 mean in [2, 8]?

**Comment by hanoonaR** [comment]
Hi @th0214 ,

Sure. 

In [2, 8], 2 corresponds to the per GPU BS of the detection dataset, and 8 corresponds to the per GPU batch size of the classification dataset. So if you are using 2 GPUs, and want to keep the effective BS as [16, 64], then the DATASET_BS must be set as [8, 32]. 

Thank you.
