### ISSUE TITLE
query about the clip classification acc using gt boxes in Object-centric

### ISSUE THREAD

**Issue by motoight** [hanoonaR/object-centric-ovd#12]
Hi, You've been down great work, and I want to reproduce some results post in your paper. Here is the problem I've met.

In your paper, you mentioned that using clip model directly on cropped imaged (using gt boxes) can gain comparable acc in top-1. Here is the table you posted.
![image](https://user-images.githubusercontent.com/39431667/203719673-1b25b8df-9b91-4955-a210-3a1c787aa592.png)

And I reproduce the experiment by following step, the code link is https://gist.github.com/motoight/44602b8ca0e51518b7017faa93541e10 :

1. cropped the image using gt bbox
2. using clip preprocess the cropped images
3. using clip model encode cropped images 
4. load coco class text embedding (generated by template "a photo of {class name}")
5. make dot product between text embedding and viusal embedding
6. pack cls_score and gt_boxes into results, get ap50 results by coco_eval api

Here is the results I got:
![image](https://user-images.githubusercontent.com/39431667/203719831-9dfb72de-01e3-46fe-a782-7aa5665058f6.png)

There is a huge gap between the result you posted in your paper, and I want to know did I make any mistakes in implementaion ? 
By the way, I've tried some tircks to improve the results:

1. generate text embedding using 81 prompts 
2. apply temperature = 0.01 and softmax on scores

Hope you can give me some help!!! 
Wish you have a nice day, thanks!!!

**Comment by hanoonaR** [comment]
Hi @motoight,

Thank you for your interest in our work. Based on the steps you have explained here, there are two differences that may be the reason for this difference:

1. The comparison you must be making from your results is with the second row in the Table. 8, which uses clip image (cropped regions) embeddings. Note that rows 1, 3, and 4 use image (cropped regions) embeddings from the OVD detector.
2.  We report top-1 accuracy, which calculates only the accuracy (in percentage). While in step 6 you have enlisted, it is mentioned that you compare AP50 with the reported numbers. 

Please verify these differences, so that we may identify the reason behind the variation in our results. 

Thank you.

**Comment by motoight** [comment]
Thanks for your kindly reply! 
Could you please tell some details on how Table8 ?
https://user-images.githubusercontent.com/39431667/203719673-1b25b8df-9b91-4955-a210-3a1c787aa592.png
cause when I use gt cropped patch and get clip classification results is below, I wonder whether I did any thing wrong?
![image](https://user-images.githubusercontent.com/39431667/209915157-1b0a70c9-9427-4f33-aa62-497c5f59b2de.png)

**Comment by motoight** [comment]
> Thanks for your kindly reply! Could you please tell some details on how Table8 ? https://user-images.githubusercontent.com/39431667/203719673-1b25b8df-9b91-4955-a210-3a1c787aa592.png cause when I use gt cropped patch and get clip classification results is below, I wonder whether I did any thing wrong? ![image](https://user-images.githubusercontent.com/39431667/209915157-1b0a70c9-9427-4f33-aa62-497c5f59b2de.png)

here is the code I wrote : https://gist.github.com/motoight/e642edd5dc2635ab655c0c1aa06c393a

**Comment by muzairkhattak** [comment]
Hi @motoight,

Thank you for responding back.

It looks like you are performing the right steps. 

However, can you verify if you are using **a combined text classifier** from text-encoder for both base and novel classes or **separate classifiers for each set**? This is important as using a single text classifier may result in less performance (generalized zero-shot setting).

Further, I am sharing a notebook containing the sample code which we used for obtaining CLIP classification scores using ground-truth boxes. You will first require to save the CLIP image encoder embeddings in pickle files. 

Kindly look into the notebook [here](https://colab.research.google.com/drive/1cDOvF8H7wHVs3wIE7nSV2ZCQnE5xSYJD?usp=sharing) and let us know in-case there is any query.

Kind regards and best of luck!

**Comment by motoight** [comment]
Hi，thanks for your kindly reply！
I do use a combined text classifier which contains 65 classes( both novel and base). I want to know how to your get clip image embeddings. I guess you just **crop the gt box region and apply clip preprocess on those cropped patches**, however, I didn't got the same results as you got, here is what I've got.
![image](https://user-images.githubusercontent.com/39431667/210352598-78cf100e-2700-4798-89dc-060ab35e028a.png)

**Comment by motoight** [comment]
By the way, I use 80 prompts to generate text embedding which means if I just use "A photo of {class name}", the acc will be lower than 0.466

**Comment by muzairkhattak** [comment]
Hi @motoight,

Thanks for you reply. 

> I guess you just crop the gt box region and apply clip preprocess on those cropped patches

Yes we are creating the image embeddings exactly like this. To be exact, we do this process during the inference process of our detector (in the [train_net.py](https://github.com/hanoonaR/object-centric-ovd/blob/main/train_net.py)) and save the image embeddings accordingly. 

Once all the image embeddings are saved (in pickle files), we use the notebook (shared earlier) to calculate the GT box accuracy.

You can try it like this and see if that helps.

It is recommended to utilize our shared notebook.

Kindly let us know if that works.

Kind regards.
