### ISSUE TITLE
Questions about the results

### ISSUE THREAD

**Issue by th0214** [hanoonaR/object-centric-ovd#13]
Hi
According to the issue #10, you have not uploaded the model checkpoints written in the current paper, so is it correct that the score for the paper does not come out even if I train it?

**Comment by mmaaz60** [comment]
Hi @th0214,

Thank you for your interest in our work. The current checkpoints and generated pseudo labels correspond to the original [MAVL](https://arxiv.org/abs/2111.11430) model. Therefore, if you train using the currently provided pseudo labels, the results will be slightly higher than the results reported in the paper.

Further, we will soon open-source the MAVL checkpoints trained with filtered annotations along with the corresponding pseudo labels. Thank you for your patience.

Please let us know if you have any further questions.

**Comment by Edwardmark** [comment]
@mmaaz60 hi, thank you for your great work. Could you tell me which mavl checkpoints is used to generate the psuedo labels in your paper, please give me a link, thanks.
