### ISSUE TITLE
Issues about ImageNet-21K

### ISSUE THREAD

**Issue by gugite** [hanoonaR/object-centric-ovd#15]
Hi, thanks for your great work!!

Due to the space limit on my machine, I cannot download and save the full ImageNet-21K dataset. 

I noticed that this work only utilizes a subset of the ImageNet-21K. Could you please share the used image sub-set with me? I really appreciate that.

My e-mail is 3405993357@qq.com

**Comment by mmaaz60** [comment]
Hi @gugite,

Thank you for your interest in our work. You can download the subset of ImageNet-21K used in our LVIS experiments at [this link](https://mbzuaiac-my.sharepoint.com/:u:/g/personal/muhammad_maaz_mbzuai_ac_ae/EQRUU3kt5IFKtHuIy9FEys4BBlmdEPUzw9xbxS7iBUAPNQ?e=2ytWP1).

Please let me know if you will have any questions. Thanks

**Comment by gugite** [comment]
Thank you so much for your quick reply!
