### ISSUE TITLE
Results for 4x schedule on LVIS?

### ISSUE THREAD

**Issue by Kyfafyd** [hanoonaR/object-centric-ovd#16]
Thanks for sharing! 
I would like to learn what about the results of 4x schedule on LVIS?

**Comment by hanoonaR** [comment]
Hi @Kyfafyd ,

Thank you for your interest in our repository. Unfortunately, We only have 8x schedule results available on LVIS, as reported in the paper. However, you can easily obtain the 4x results by running the code. We would be happy to assist you with any questions or issues you may have while doing so.

Thank you.
