### ISSUE TITLE
Open images weights 

### ISSUE THREAD

**Issue by ma-siddiqui** [hanoonaR/object-centric-ovd#17]
Hi,

Please share the weights of model trained on open images?

Thanks

**Comment by hanoonaR** [comment]
Hi @ma-siddiqui ,

Thank you for your interest in our work and apologies for the delayed response. But please note the performance we report on OpenImages is the cross-dataset (zero-shot) evaluation of our best LVIS model, which is the Detic-based CenterNet model. We have not included these models in our repository and therefore sharing the weights wouldn't be helpful. But please let us know if you would like to know any implementational details.

Thank you.
