### ISSUE TITLE
Reproduce the cross-dataset evaluation

### ISSUE THREAD

**Issue by Changes92** [hanoonaR/object-centric-ovd#20]
Thank you for your great work!

Recently, I hoped to reproduce the cross-data evaluation but failed to obtain the reported results. Could you please provide the following files? 1) the YAML config file, 2) the files in ./ovd/datasets/, and 3) the CLIP word embedding? 

Thank you so much!

**Comment by hanoonaR** [comment]
Hi @tmp12316 ,

Thank you for showing your interest in our work. Please note the performance we report on OpenImages and Objects365 cross-dataset is the zero-shot evaluation of our best LVIS model, which is the Detic-based CenterNet model. We have not included these models in our repository and therefore sharing the requested files wouldn't be helpful. But please let us know if you would like to know any implementational details.

Thank you.
