### ISSUE TITLE
Missing coco_props.tar.gz

### ISSUE THREAD

**Issue by hq-deng** [hanoonaR/object-centric-ovd#4]
Thanks for your great work. I found the link to coco_props.tar.gz is wrong. Could you please share it again and check the link?

**Comment by hanoonaR** [comment]
Hi @hq-deng ,

Thank you for raising this issue. 

You may download the class specific and class-agnostic MAVL proposals on the COCO datasets from [here](https://mbzuaiac-my.sharepoint.com/:u:/g/personal/hanoona_bangalath_mbzuai_ac_ae/EeJuo844j8FIsnuiX3wBxCgBcBR2MSjbhiLCuA4OC2cSWg?e=5BeESO). The links have also been updated in the [DATASETS.md](https://github.com/hanoonaR/object-centric-ovd/edit/main/docs/DATASETS.md). Hope this helps.

**Comment by hq-deng** [comment]
Thank you.
