### ISSUE TITLE
JSONDecodeError

### ISSUE THREAD

**Issue by Millielele** [hanoonaR/object-centric-ovd#7]
Thanks for your excellent work. 
When i run LVIS open vocabulary, the code shows  
"Loaded 100170 images in the LVIS v1 format from datasets/lvis/lvis_v1_train_norare.json"
then, it has an issue:
json.decoder.JSONDecodeError: Expecting value: line 1 column 212809574 (char 212809573)
Why this happen?How can i solve that?

**Comment by mmaaz60** [comment]
Hi @Millielele,

Thank you for your interest in our work. It looks like a dataset problem which we have not encountered before. Please double check if you have all required annotation files in the correct form. Further,  please provide details on how I can reproduce this bug. Thanks

**Comment by Millielele** [comment]
Thanks for your reply @mmaaz60 ,
This happens when i run "python train_net.py --num-gpus 4 --config-file /XX/openOD/configs/lvis/LVIS_OVD_Base_PIS.yaml". 
I want to know if code including PIS in open-vocabulary LVIS must need Image-Net 21K dataset.

**Comment by hanoonaR** [comment]
Hi @Millielele ,

The LVIS OVD experiment for PIS using the [configuration](https://github.com/hanoonaR/object-centric-ovd/blob/main/configs/lvis/LVIS_OVD_Base_PIS.yaml) utilizes pseudo image-level supervision on ImageNet21K. It therefore requires the ImageNet 21K dataset and pseudo labels predicted on them which are present in the provided JSON `imagenet_lvis_image_info_pis.json`.  

If you continue to face any issue, kindly get back to us. Thank you.

**Comment by Millielele** [comment]
Thanks a lot
