### ISSUE TITLE
Using your pretrained models for ZSD on custom objects and images

### ISSUE THREAD

**Issue by Ozziko** [hanoonaR/object-centric-ovd#8]
Hi guys, great work (!), but it's too hard to try your pretrained models (and maybe cite you) for other tasks that require zero-shot detection on custom objects and custom images...

Detic published a great simple colab notebook for this (I'm not related to them, just impressed). I'm sure that if you write a similar notebook you'll become much more attractive for others to use your code/models :-)
Thanks!

**Comment by mmaaz60** [comment]
Hi @Ozziko,

Thank you for your interest in our work. Following your suggestion, we have added an interactive _Colab Demo_  for our method. [![Colab Demo](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/drive/19LBqQg0cS36rTLL_TaXZ7Ka9KJGkxiSe?usp=sharing).

The demo provides the following features,
* Overview of the inference process of our Object Centric OVD approach.
* Supports detecting visual concepts using COCO and LVIS vocabularies.
* Creates your own detector by changing the classifier head!
